name: CI Pipeline

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: installing node fpr cml
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Using for Datascience
        uses: iterative/setup-cml@v1

      - name: Running dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Main File
        run: python main.py

      - name: Publish Image
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml publish foo.png --md >> report.md

      - name: Create Report Using CML
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'My first CML report' >> report.md
          echo '![](./plot.png)' >> report.md
          cml comment create --publish report.md
